#spring:
##  mvc:
##    static-path-pattern: /res/**
#  resources:
#    static-locations: classpath:/static/

#spring:
#  resources:
#    add-mappings: false

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true   #开启页面表单的Rest功能